
version: 2

models:
    - name: menacing_ratings
      description: "takes all movies with keyword menace in mpaa rating "
      columns:
          - name: id
            tests:
                - unique
                - not_null
          - name: movie_id
            tests:
                - not_null

    - name: menacing_movies
      description: "join with movie_sample table, extracts the rating level from mpaa ratings"
      columns:
          - name: ratings      
            tests:
                - not_null
                
    - name: menacing_runtimes
      description: "extract country from runtime column for menacing movies"
      columns:
          - name: country      
            tests:
                - not_null
                
    - name: menacing_gross_countries
      description: "extract country from gross column for menacing movies"
      columns:
          - name: country      
            tests:
                - not_null