version: 2

sources:
    - name: imdb
      database: imdb
      schema: public
      tables:
         - name: info_type
         - name: actor_sample
         - name: cast_sample
         - name: movie_info_sample
         - name: movie_sample
         - name: role_type
#          - name: 
#          - name: 
#          - name: 
#          - name: 
#          - name: 
         